<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="11" passed="9" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-02-13T16:35:48 IST" name="Default suite" finished-at="2024-02-13T16:37:51 IST" duration-ms="122685">
    <groups>
    </groups>
    <test started-at="2024-02-13T16:35:48 IST" name="Default test" finished-at="2024-02-13T16:37:51 IST" duration-ms="122685">
      <class name="Error.Console_log.Atlas_consolelog">
        <test-method is-config="true" signature="setup()[pri:0, instance:Error.Console_log.Atlas_consolelog@54e1c68b]" started-at="2024-02-13T16:35:48 IST" name="setup" finished-at="2024-02-13T16:35:50 IST" duration-ms="2014" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="login()[pri:1, instance:Error.Console_log.Atlas_consolelog@54e1c68b]" started-at="2024-02-13T16:35:50 IST" name="login" finished-at="2024-02-13T16:36:00 IST" duration-ms="9968" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method signature="series_set()[pri:2, instance:Error.Console_log.Atlas_consolelog@54e1c68b]" started-at="2024-02-13T16:36:00 IST" name="series_set" finished-at="2024-02-13T16:36:17 IST" duration-ms="17007" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- series_set -->
        <test-method signature="atlaseditor()[pri:3, instance:Error.Console_log.Atlas_consolelog@54e1c68b]" started-at="2024-02-13T16:36:17 IST" name="atlaseditor" finished-at="2024-02-13T16:36:25 IST" duration-ms="8114" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[SEVERE logs were found in the console. expected [0] but found [9]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: SEVERE logs were found in the console. expected [0] but found [9]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at Error.Console_log.Atlas_consolelog.checkConsoleLog(Atlas_consolelog.java:379)
at Error.Console_log.Atlas_consolelog.atlaseditor(Atlas_consolelog.java:193)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- atlaseditor -->
        <test-method signature="Editmenu()[pri:4, instance:Error.Console_log.Atlas_consolelog@54e1c68b]" started-at="2024-02-13T16:36:25 IST" name="Editmenu" finished-at="2024-02-13T16:36:28 IST" duration-ms="2625" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Editmenu -->
        <test-method signature="contributor()[pri:5, instance:Error.Console_log.Atlas_consolelog@54e1c68b]" started-at="2024-02-13T16:36:28 IST" name="contributor" finished-at="2024-02-13T16:36:33 IST" duration-ms="5099" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[SEVERE logs were found in the console. expected [0] but found [2]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: SEVERE logs were found in the console. expected [0] but found [2]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at Error.Console_log.Atlas_consolelog.checkConsoleLog(Atlas_consolelog.java:379)
at Error.Console_log.Atlas_consolelog.contributor(Atlas_consolelog.java:237)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- contributor -->
        <test-method signature="draw()[pri:6, instance:Error.Console_log.Atlas_consolelog@54e1c68b]" started-at="2024-02-13T16:36:33 IST" name="draw" finished-at="2024-02-13T16:36:36 IST" duration-ms="2908" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- draw -->
        <test-method signature="annotation()[pri:7, instance:Error.Console_log.Atlas_consolelog@54e1c68b]" started-at="2024-02-13T16:36:36 IST" name="annotation" finished-at="2024-02-13T16:36:55 IST" duration-ms="19214" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- annotation -->
        <test-method signature="save()[pri:8, instance:Error.Console_log.Atlas_consolelog@54e1c68b]" started-at="2024-02-13T16:36:55 IST" name="save" finished-at="2024-02-13T16:37:00 IST" duration-ms="4855" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- save -->
        <test-method signature="back()[pri:9, instance:Error.Console_log.Atlas_consolelog@54e1c68b]" started-at="2024-02-13T16:37:00 IST" name="back" finished-at="2024-02-13T16:37:04 IST" duration-ms="4688" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- back -->
        <test-method signature="retrive()[pri:10, instance:Error.Console_log.Atlas_consolelog@54e1c68b]" started-at="2024-02-13T16:37:04 IST" name="retrive" finished-at="2024-02-13T16:37:33 IST" duration-ms="28368" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- retrive -->
        <test-method signature="delete()[pri:11, instance:Error.Console_log.Atlas_consolelog@54e1c68b]" started-at="2024-02-13T16:37:33 IST" name="delete" finished-at="2024-02-13T16:37:50 IST" duration-ms="17659" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- delete -->
        <test-method is-config="true" signature="close()[pri:0, instance:Error.Console_log.Atlas_consolelog@54e1c68b]" started-at="2024-02-13T16:37:50 IST" name="close" finished-at="2024-02-13T16:37:51 IST" duration-ms="119" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
      </class> <!-- Error.Console_log.Atlas_consolelog -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
